# Generated by Django 2.2.5 on 2020-03-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20200327_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
