# Generated by Django 2.2.5 on 2020-03-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_auto_20200327_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
