# Generated by Django 2.2.5 on 2020-03-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20200327_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Your Order'},
        ),
    ]
